# Generated by Django 5.0.6 on 2024-07-04 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DondeLaFlaca', '0002_delete_producto_delete_tipo_producto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id_forma_pago', models.AutoField(db_column='idFormaPago', primary_key=True, serialize=False)),
                ('forma', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Formas de pago',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(db_column='idProducto', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(blank=True, max_length=30, null=True)),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('foto', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id_tipo_producto', models.AutoField(db_column='idTipoProducto', primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id_tipo_usuario', models.AutoField(db_column='idTipoUsuario', primary_key=True, serialize=False)),
                ('tipo', models.CharField(db_column='Tipo de Usuario', max_length=30)),
                ('descripcion', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(db_column='idPago', primary_key=True, serialize=False)),
                ('total', models.IntegerField()),
                ('domicilio', models.BooleanField()),
                ('id_forma_pago', models.ForeignKey(db_column='idFormaPago', on_delete=django.db.models.deletion.CASCADE, to='DondeLaFlaca.formapago')),
            ],
        ),
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id_despacho', models.AutoField(db_column='idDespacho', primary_key=True, serialize=False)),
                ('pedido', models.DateTimeField(blank=True, null=True)),
                ('envio', models.DateTimeField(blank=True, null=True)),
                ('recibo', models.DateTimeField(blank=True, null=True)),
                ('id_pago', models.ForeignKey(db_column='idPago', on_delete=django.db.models.deletion.CASCADE, to='DondeLaFlaca.pago')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id_detalle', models.AutoField(db_column='idDetalle', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.IntegerField()),
                ('id_pago', models.ForeignKey(db_column='idPago', on_delete=django.db.models.deletion.CASCADE, to='DondeLaFlaca.pago')),
                ('id_producto', models.ForeignKey(db_column='idProducto', on_delete=django.db.models.deletion.CASCADE, to='DondeLaFlaca.producto')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='id_tipo_producto',
            field=models.ForeignKey(db_column='idTipoProducto', on_delete=django.db.models.deletion.CASCADE, to='DondeLaFlaca.tipoproducto'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('id_tipo_usuario', models.ForeignKey(db_column='idTipoUsuario', on_delete=django.db.models.deletion.CASCADE, to='DondeLaFlaca.tipousuario')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pago',
            name='rut',
            field=models.ForeignKey(db_column='rut', on_delete=django.db.models.deletion.CASCADE, to='DondeLaFlaca.usuario'),
        ),
    ]
