# Generated by Django 5.0.6 on 2024-07-05 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DondeLaFlaca', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id_carrito', models.AutoField(db_column='idCarrito', primary_key=True, serialize=False)),
                ('rut', models.ForeignKey(db_column='rut', on_delete=django.db.models.deletion.CASCADE, to='DondeLaFlaca.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id_item', models.AutoField(db_column='idItem', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('id_carrito', models.ForeignKey(db_column='idCarrito', on_delete=django.db.models.deletion.CASCADE, to='DondeLaFlaca.carrito')),
                ('id_producto', models.ForeignKey(db_column='idProducto', on_delete=django.db.models.deletion.CASCADE, to='DondeLaFlaca.producto')),
            ],
        ),
    ]
