# Generated by Django 5.0.6 on 2024-07-06 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DondeLaFlaca', '0004_carrito_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
