# Generated by Django 5.0.6 on 2024-07-13 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DondeLaFlaca', '0005_alter_producto_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='subtotal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
